import { afterEach, beforeEach, describe, expect, it } from "vitest";
import fs from "node:fs"; import os from "node:os"; import path from "node:path";
import { addAcademicRecords, appendMessage, createUser, deleteAcademicRecord, deleteOwnedSession, findUserByEmail, getOwnedSession, listMessages, saveOwnedSession, studentRecords, teacherRecords, updateUserPassword } from "../src/server/data/store";
import type { ConversationSession } from "../src/server/types/session";
let tempDir="";
beforeEach(()=>{tempDir=fs.mkdtempSync(path.join(os.tmpdir(),"advisor-store-"));process.env.DATA_DIR=tempDir;delete process.env.DATABASE_URL;});
afterEach(()=>{fs.rmSync(tempDir,{recursive:true,force:true});delete process.env.DATA_DIR;});
function session(ownerId:string):ConversationSession{const now=Date.now();return{sessionId:"session-test-123",ownerId,roleId:"co-van-hoc-duong",rollingSummary:"",stableFacts:[],recentTurns:[],createdAt:now,updatedAt:now,totalTurns:0,customPersona:{enabled:false}}}
describe("storage adapter",()=>{
 it("stores users and enforces unique fields",async()=>{const u=await createUser({email:"HS001@example.com",name:"An",role:"student",passwordHash:"hash",studentCode:"HS001"});expect((await findUserByEmail("hs001@example.com"))?.id).toBe(u.id);await expect(createUser({email:"other@example.com",name:"B",role:"student",passwordHash:"hash",studentCode:"hs001"})).rejects.toThrow("STUDENT_CODE_EXISTS")});
 it("isolates and deletes sessions",async()=>{const s=session("owner-a");await saveOwnedSession(s);await appendMessage(s.sessionId,s.ownerId,{role:"user",content:"Xin chào",timestamp:Date.now()});expect((await getOwnedSession(s.sessionId,"owner-a"))?.sessionId).toBe(s.sessionId);expect(await getOwnedSession(s.sessionId,"owner-b")).toBeUndefined();expect(await listMessages(s.sessionId,"owner-a")).toHaveLength(1);expect(await deleteOwnedSession(s.sessionId,"owner-a")).toBe(true);expect(await listMessages(s.sessionId,"owner-a")).toBeNull()});
 it("upserts academic rows and matches student",async()=>{const u=await createUser({email:"student@example.com",name:"Nguyễn An",role:"student",passwordHash:"hash",studentCode:"HS001"});const base={studentId:"HS001",studentName:"Nguyễn An",className:"10A1",subject:"Toán",semester:"HK1",teacherId:"teacher-1"};await addAcademicRecords([{...base,score:7.5}]);await addAcademicRecords([{...base,score:8.5}]);expect(await teacherRecords("teacher-1")).toHaveLength(1);expect((await studentRecords(u))[0].score).toBe(8.5)});
 it("stores different assessment types for the same subject and semester",async()=>{const base={studentId:"HS003",studentName:"Chi",className:"10A3",subject:"Toán",semester:"HK1",teacherId:"teacher-1"};await addAcademicRecords([{...base,assessmentType:"15 phút",note:"Lần 1",score:7},{...base,assessmentType:"Giữa kỳ",note:"",score:8.5}]);const records=await teacherRecords("teacher-1");expect(records).toHaveLength(2);expect(new Set(records.map(r=>r.assessmentType))).toEqual(new Set(["15 phút","Giữa kỳ"]));});
 it("updates only the matching assessment type",async()=>{const base={studentId:"HS004",studentName:"Dung",className:"10A4",subject:"Văn",semester:"HK1",teacherId:"teacher-1"};await addAcademicRecords([{...base,assessmentType:"Miệng",note:"Cũ",score:6},{...base,assessmentType:"15 phút",note:"",score:7}]);await addAcademicRecords([{...base,assessmentType:"Miệng",note:"Đã sửa",score:9}]);const records=await teacherRecords("teacher-1");expect(records).toHaveLength(2);expect(records.find(r=>r.assessmentType==="Miệng")?.score).toBe(9);expect(records.find(r=>r.assessmentType==="Miệng")?.note).toBe("Đã sửa");});
 it("deletes one academic record without removing the student",async()=>{const base={studentId:"HS002",studentName:"Bình",className:"10A2",semester:"HK1",teacherId:"teacher-1"};await addAcademicRecords([{...base,subject:"Toán",score:8},{...base,subject:"Văn",score:7}]);const records=await teacherRecords("teacher-1");expect(await deleteAcademicRecord(records[0].id,"teacher-1")).toBe(true);expect(await teacherRecords("teacher-1")).toHaveLength(1);expect(await deleteAcademicRecord(records[1].id,"other-teacher")).toBe(false)});
 it("keeps backup files locally",async()=>{await createUser({email:"first@example.com",name:"First",role:"teacher",passwordHash:"hash"});await createUser({email:"second@example.com",name:"Second",role:"teacher",passwordHash:"hash"});expect(fs.existsSync(path.join(tempDir,"users.json.bak"))).toBe(true)});
 it("rejects mixed teachers",async()=>{await expect(addAcademicRecords([{studentId:"S1",studentName:"A",className:"1A",subject:"Toán",semester:"HK1",score:8,teacherId:"T1"},{studentId:"S2",studentName:"B",className:"1A",subject:"Văn",semester:"HK1",score:7,teacherId:"T2"}])).rejects.toThrow("MIXED_TEACHERS")});
 it("requires existing session for append",async()=>{await expect(appendMessage("missing","owner",{role:"user",content:"hello",timestamp:Date.now()})).rejects.toThrow("SESSION_NOT_FOUND")});
 it("tracks first-login password state",async()=>{const u=await createUser({email:"change@gmail.com",name:"Student",role:"student",studentCode:"PV002",passwordHash:"temporary",mustChangePassword:true});expect((await findUserByEmail(u.email))?.mustChangePassword).toBe(true);await updateUserPassword(u.id,"new-hash",false);expect((await findUserByEmail(u.email))?.mustChangePassword).toBe(false)});
});
