import type { RiskLevel } from "../prompts/safety";
export type ChatHistoryMessage={role:"user"|"assistant";content:string};
export interface CrisisAssessment{riskLevel:RiskLevel;shouldBypassModel:boolean;matchedTerms:string[];reasons:string[];flags:{selfHarm:boolean;suicide:boolean;violence:boolean;coercion:boolean;panic:boolean;immediateDanger:boolean;medicalWarning:boolean};}
const norm=(s:string)=>s.toLowerCase().normalize("NFC").replace(/\s+/g," ").trim();
const hit=(t:string,p:string[])=>p.filter(x=>t.includes(x));
const negated=(text:string,term:string)=>{const i=text.indexOf(term);if(i<0)return false;const pre=text.slice(Math.max(0,i-24),i);return /(?:không|chưa|chẳng|đừng|không hề)\s*$/.test(pre);};
const active=(text:string,patterns:string[])=>patterns.filter(p=>text.includes(p)&&!negated(text,p));
const SUICIDE=["tự tử","muốn chết","không muốn sống","kết thúc cuộc đời","tự làm hại bản thân","cắt tay","uống thuốc quá liều","nhảy lầu","treo cổ"];
const SELF=["muốn làm đau bản thân","không chịu nổi nữa","hết cách rồi","muốn biến mất khỏi đây"];
const VIOLENCE=["bạo lực gia đình","bị đánh","đánh em","dọa đánh","đe dọa","khống chế","nhốt","đuổi khỏi nhà","cưỡng ép"];
const COERCION=["ép em","bị ép","bị kiểm soát","không cho ra ngoài","bắt phải làm"];
const PANIC=["hoảng loạn","khó thở","tim đập nhanh","không thở nổi","muốn ngất","quá sợ","không kiểm soát được"];
const NOW=["ngay bây giờ","lúc này","bây giờ","đang ở đây","đang xảy ra","tối nay","sắp làm","có kế hoạch","có dao","có thuốc"];
const MEDICAL=["đau ngực","ngất","co giật","không thở được","mất ý thức"];
export function assessCrisisRisk(input:{message:string;history?:ChatHistoryMessage[]}):CrisisAssessment{const current=norm(input.message);const history=norm((input.history??[]).filter(x=>x.role==="user").slice(-4).map(x=>x.content).join(" "));const suicide=active(current,SUICIDE),self=active(current,SELF),violence=active(current,VIOLENCE),coercion=active(current,COERCION),panic=active(current,PANIC),now=hit(current,NOW),medical=hit(current,MEDICAL);const pastConcern=active(history,[...SUICIDE,...VIOLENCE,...COERCION]).length>0;const flags={selfHarm:suicide.length>0||self.length>0,suicide:suicide.length>0,violence:violence.length>0,coercion:coercion.length>0,panic:panic.length>0,immediateDanger:now.length>0,medicalWarning:medical.length>0};let riskLevel:RiskLevel="safe",shouldBypassModel=false;const reasons:string[]=[];if((flags.suicide&&flags.immediateDanger)||((flags.violence||flags.coercion)&&flags.immediateDanger)){riskLevel="high_risk";shouldBypassModel=true;reasons.push("Có dấu hiệu nguy hiểm hiện tại cần ưu tiên hỗ trợ trực tiếp.");}else if(flags.suicide||flags.selfHarm||flags.violence||flags.coercion||flags.panic||flags.medicalWarning||pastConcern){riskLevel="distress";reasons.push("Có dấu hiệu đau khổ hoặc mất an toàn cần phản hồi thận trọng.");}return{riskLevel,shouldBypassModel,matchedTerms:[...new Set([...suicide,...self,...violence,...coercion,...panic,...now,...medical])],reasons,flags};}
