"use client";
import { useEffect,useState } from "react";
type Identity={id:string;role:"guest"|"student"|"teacher";name:string;email?:string};
type RecordRow={id:string;studentId:string;studentName:string;className:string;subject:string;semester:string;score:number};
export default function AccountPanel(){const[id,setId]=useState<Identity|null>(null);const[email,setEmail]=useState("");const[name,setName]=useState("");const[password,setPassword]=useState("");const[studentCode,setStudentCode]=useState("");const[role,setRole]=useState<"student"|"teacher">("student");const[error,setError]=useState("");const[records,setRecords]=useState<RecordRow[]>([]);
async function json(url:string,options?:RequestInit){const r=await fetch(url,{...options,headers:{"Content-Type":"application/json",...(options?.headers||{})}});const d=await r.json();if(!r.ok)throw new Error(d.error||"Có lỗi xảy ra");return d;}
async function refresh(){const d=await json("/api/auth/me");setId(d.identity);}
async function loadRecords(identity:Identity){if(identity.role==="guest"){setRecords([]);return;}try{const d=await json(identity.role==="student"?"/api/academic/me":"/api/academic/students");setRecords(d.records);}catch{setRecords([]);}}
useEffect(()=>{void refresh();},[]);useEffect(()=>{if(id)void loadRecords(id);},[id]);
async function login(){try{setError("");const d=await json("/api/auth/login",{method:"POST",body:JSON.stringify({email,password})});setId(d.identity);}catch(e){setError(e instanceof Error?e.message:"Đăng nhập thất bại");}}
async function register(){try{setError("");const d=await json("/api/auth/register",{method:"POST",body:JSON.stringify({email,password,name,role,studentCode})});setId(d.identity);}catch(e){setError(e instanceof Error?e.message:"Đăng ký thất bại");}}
async function logout(){const d=await json("/api/auth/logout",{method:"POST",body:"{}"});setId(d.identity);setRecords([]);localStorage.removeItem("clinic-chat-session-id");location.reload();}
async function upload(file:File){const f=new FormData();f.append("file",file);const r=await fetch("/api/academic/import",{method:"POST",body:f});const d=await r.json();if(!r.ok){setError(d.error);return;}setError(`Đã nhập ${d.count} dòng hợp lệ.`);if(id)void loadRecords(id);}
if(!id)return <section className="panel-card">Đang khởi tạo phiên an toàn…</section>;
return <section className="panel-card" aria-label="Tài khoản"><div className="panel-title">Tài khoản và dữ liệu học tập</div>{id.role==="guest"?<><p className="panel-desc">Khách vẫn được tư vấn mà không cần đăng nhập. Lịch sử khách được bảo vệ bằng cookie phiên riêng.</p><input className="text-input" placeholder="Họ tên" value={name} onChange={e=>setName(e.target.value)}/><input className="text-input" placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)}/><input className="text-input" type="password" placeholder="Mật khẩu (ít nhất 8 ký tự)" value={password} onChange={e=>setPassword(e.target.value)}/><select className="select-input" value={role} onChange={e=>setRole(e.target.value as "student"|"teacher")}><option value="student">Học sinh / sinh viên</option><option value="teacher">Giáo viên</option></select>{role==="student"&&<input className="text-input" placeholder="Mã học sinh / sinh viên (khớp file vnEdu)" value={studentCode} onChange={e=>setStudentCode(e.target.value)}/>}<div style={{display:"flex",gap:8,marginTop:8}}><button className="secondary-button" onClick={login}>Đăng nhập</button><button className="primary-button" onClick={register}>Tạo tài khoản</button></div></>:<><p><strong>{id.name}</strong> · {id.role==="student"?"Học sinh / sinh viên":"Giáo viên"}</p><button className="secondary-button" onClick={logout}>Đăng xuất</button>{id.role==="teacher"&&<label className="field-label" style={{marginTop:12}}>Nhập XLSX/CSV từ vnEdu<input type="file" accept=".xlsx,.csv" onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f);}}/></label>}<div style={{maxHeight:220,overflow:"auto",marginTop:10}}>{records.length===0?<p className="panel-desc">Chưa có dữ liệu học tập phù hợp.</p>:records.slice(0,40).map(r=><div key={r.id} style={{padding:"7px 0",borderBottom:"1px solid var(--line)"}}><strong>{r.studentName}</strong> · {r.subject}: {r.score}/10<br/><small>{r.className} {r.semester}</small></div>)}</div></>}{error&&<p className="error-text">{error}</p>}</section>}
