"use client";
import { useEffect, useMemo, useRef, useState } from "react";
type Identity={id:string;role:"guest"|"student"|"teacher";name:string;email?:string;mustChangePassword?:boolean};
type Row={id:string;studentId:string;studentName:string;className:string;subject:string;semester:string;score:number};
async function api(url:string,options?:RequestInit){const r=await fetch(url,{...options,credentials:"same-origin",headers:options?.body instanceof FormData?options.headers:{"Content-Type":"application/json",...(options?.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.details?.join("\n")||d.error||"Có lỗi xảy ra");return d;}
export default function AccountPanel(){
 const[identity,setIdentity]=useState<Identity|null>(null),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[newPassword,setNewPassword]=useState(""),[confirm,setConfirm]=useState(""),[feedback,setFeedback]=useState<string>(""),[records,setRecords]=useState<Row[]>([]),[busy,setBusy]=useState(false);const fileRef=useRef<HTMLInputElement|null>(null);
 async function refresh(){const d=await api("/api/auth/me");setIdentity(d.identity);} async function load(i:Identity){if(i.role==="guest")return setRecords([]);const d=await api(i.role==="student"?"/api/academic/me":"/api/academic/students");setRecords(d.records||[]);} useEffect(()=>{void refresh()},[]);useEffect(()=>{if(identity)void load(identity).catch(()=>setRecords([]))},[identity]);
 const summary=useMemo(()=>({students:new Set(records.map(r=>r.studentId)).size,avg:records.length?records.reduce((a,b)=>a+b.score,0)/records.length:0}),[records]);
 async function login(){setBusy(true);setFeedback("");try{const d=await api("/api/auth/login",{method:"POST",body:JSON.stringify({email,password})});setIdentity(d.identity);setPassword("");if(d.requirePasswordChange)setFeedback("Bạn phải đổi mật khẩu trước khi sử dụng hệ thống.");else setFeedback("Đăng nhập thành công.");}catch(e){setFeedback(e instanceof Error?e.message:"Đăng nhập thất bại")}finally{setBusy(false)}}
 async function changePassword(){if(newPassword.length<8)return setFeedback("Mật khẩu mới cần ít nhất 8 ký tự.");if(newPassword!==confirm)return setFeedback("Hai mật khẩu không khớp.");setBusy(true);try{const d=await api("/api/auth/change-password",{method:"POST",body:JSON.stringify({password:newPassword})});setIdentity(d.identity);setNewPassword("");setConfirm("");setFeedback("Đổi mật khẩu thành công.");location.reload();}catch(e){setFeedback(e instanceof Error?e.message:"Không thể đổi mật khẩu")}finally{setBusy(false)}}
 async function logout(){await api("/api/auth/logout",{method:"POST",body:"{}"});localStorage.removeItem("clinic-chat-session-id");location.reload();}
 async function upload(file:File){setBusy(true);setFeedback("");try{const f=new FormData();f.append("file",file);const d=await api("/api/academic/import",{method:"POST",body:f});setFeedback(`Đã nhập ${d.count} điểm và tạo ${d.createdAccounts} tài khoản học sinh. Mật khẩu mặc định: 123456.`);if(identity)await load(identity);}catch(e){setFeedback(e instanceof Error?e.message:"Nhập file thất bại")}finally{setBusy(false);if(fileRef.current)fileRef.current.value=""}}
 if(!identity)return <section className="panel-card">Đang tải…</section>;
 if(identity.role==="student"&&identity.mustChangePassword)return <section className="panel-card account-panel"><div className="panel-title">Đổi mật khẩu lần đầu</div><p className="panel-desc">Tài khoản do giáo viên cấp. Hãy đặt mật khẩu riêng trước khi tiếp tục.</p><label><span>Mật khẩu mới</span><input className="text-input" type="password" value={newPassword} onChange={e=>setNewPassword(e.target.value)} minLength={8}/></label><label><span>Nhập lại mật khẩu</span><input className="text-input" type="password" value={confirm} onChange={e=>setConfirm(e.target.value)}/></label><button className="primary-button full-button" onClick={()=>void changePassword()} disabled={busy}>Lưu mật khẩu mới</button>{feedback&&<div className="account-feedback error">{feedback}</div>}</section>;
 return <section className="panel-card account-panel"><div className="account-heading"><div><div className="panel-title">Đăng nhập hệ thống</div><div className="panel-desc">Sử dụng tài khoản do nhà trường cấp để tiếp tục.</div></div><span className={`role-chip role-${identity.role}`}>{identity.role==="guest"?"Khách":identity.role==="teacher"?"Giáo viên":"Học sinh"}</span></div>
 {identity.role==="guest"?<div className="auth-form"><div className="privacy-card"><div><strong>Tài khoản được quản lý bởi nhà trường</strong><p>Học sinh sử dụng thông tin đăng nhập do giáo viên phụ trách cung cấp.</p></div></div><label><span>Email</span><input className="text-input" type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label><span>Mật khẩu</span><input className="text-input" type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label><button className="primary-button full-button" onClick={()=>void login()} disabled={busy}>{busy?"Đang xác thực…":"Đăng nhập"}</button><small>Nếu chưa có tài khoản hoặc quên mật khẩu, vui lòng liên hệ giáo viên phụ trách.</small></div>:<><div className="profile-card"><div className="avatar">{identity.name[0]}</div><div><strong>{identity.name}</strong><p>{identity.email}</p></div><button className="icon-button" onClick={()=>void logout()}>↗</button></div>{identity.role==="teacher"&&<><a className="primary-button full-button" href="/teacher">Đi tới trang quản trị</a><div className="metric-grid"><div><strong>{records.length}</strong><span>Bản ghi</span></div><div><strong>{summary.students}</strong><span>Học sinh</span></div><div><strong>{records.length?summary.avg.toFixed(1):"—"}</strong><span>Điểm TB</span></div></div><a className="primary-button full-button" href="/mau-import-hoc-sinh.xlsx" download>Tải biểu mẫu Excel</a><div className="upload-zone"><input ref={fileRef} id="academic-file" className="sr-only" type="file" accept=".xlsx,.csv" onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f)}}/><label htmlFor="academic-file"><strong>{busy?"Đang xử lý…":"Nhập dữ liệu học sinh"}</strong><small>Hỗ trợ Excel/CSV theo đúng biểu mẫu của hệ thống</small></label></div></>}
 <div className="record-list">{records.slice(0,30).map(r=><article className="record-row" key={r.id}><div><strong>{identity.role==="teacher"?r.studentName:r.subject}</strong><span>{r.studentId} · {r.className} · {r.semester}</span></div><div className="score-badge">{r.score.toFixed(1)}</div></article>)}</div></>}{feedback&&<div className="account-feedback" style={{whiteSpace:"pre-wrap"}}>{feedback}</div>}</section>;
}
